[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "python-straight-to-the-point"
authors = [{name = "Lourenço", email = "costa2016@pm.me"}]
dynamic = ["version", "description"]
